// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IMajesticonsPencilAlt: typeof import('~icons/majesticons/pencil-alt')['default']
}
export {}
